name: geomag
description: Translate GPS location data to geo-magnetic data such as magnetic declination.
version: 0.1.0
homepage: https://github.com/jifalops/geomag
author: Jacob Phillips <jifalops@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  intl: ^0.15.8
  meta: ^1.1.6

dev_dependencies:
  pedantic: ^1.8.0+1
  test: ^1.6.5