name: geomag
description: Translate GPS location data to geo-magnetic data such as magnetic declination.
version: 0.1.1
homepage: https://github.com/jifalops/geomag

environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies:
  intl:
  meta:

dev_dependencies:
  pedantic: ^1.8.0+1
  test: ^1.6.5